-- MawashiDZ Phase 0 Final — database bootstrap
--
-- For Supabase SQL Editor: paste the full contents of
--   migrations/20260720_phase0_final.sql
-- (psql supports: \ir migrations/20260720_phase0_final.sql)
--
-- Idempotent: safe to execute multiple times.
