[build]
  publish = "netlify-hold"
  edge_functions = "netlify/edge-functions"

[functions]
  directory = "netlify-disabled-functions"
  node_bundler = "esbuild"

[[edge_functions]]
  function = "pii-hold"
  path = "/*"
